### PR TITLE
[Feature] Data packages

### PR DESCRIPTION
**Pull request by solvedDev**
This PR tracks the progress on adding support for multiple target platforms to bridge. v2

### CODE REVIEW

**Comment by Joelant05** [comment]
I think we should put `themes/` and `extension Tags.json` in the `common` package
Is there anything else you think should be put in there?

**Comment by Joelant05** [comment]
Maybe `packIcon.png` as well

**Comment by solvedDev** [comment]
I agree those two should go into the common package

**Comment by solvedDev** [comment]
I just went for the structure that gave us a version that immediately worked correctly again

**Comment by Joelant05** [comment]
👍I will push this with the code changed appropriately where these paths are referenced

**Comment by solvedDev** [comment]
Gonna merge this into `dev` because everything seems to be working now

**Pull request merged**
