### PR TITLE
Fixed mute button https://trello.com/c/iRjVkIty

### PR DESCRIPTION
**Pull request by outercloudstudio**
## Description
Before this fix mute button would play a sound when muting and not play a sound when unmuting. I also changed en.ts to make it more clear what the button was doing.

## Motivation and Context
This fixes [this card](https://trello.com/c/iRjVkIty) on the trello board.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have tested my changes and confirmed that they are working

### CODE REVIEW

**Comment by outercloudstudio** [comment]
I just tested the newest nightly build and it seems like the audio's location changes from the dev to the build. Should this normally happen? Audio manager tries to load the file from `/audio/audioName`. What should this be instead?

**Comment by outercloudstudio** [comment]
I've made the path `./audio/audioName` instead in case that fixes it.

**Comment by solvedDev** [comment]
The intention for this card was to persist the setting upon multiple sessions which is not the case at the moment afaik. But thanks for this change too, makes more sense this way 👍

**Comment by outercloudstudio** [comment]
This is a potential fix for [this issue](https://github.com/bridge-core/editor/issues/30). It works on the dev build but I mostly want to see if it works on the nightly build. It changed the audioManager's directory to be a link to the raw file on github since the original path would not exist on the nightly versions.

**Comment by solvedDev** [comment]
I don't think this is the best way to fix the issue. I believe we should use the `process.env.BASE_URL` env variable to tweak the audio location. See https://github.com/bridge-core/editor/blob/main/src/components/App/ServiceWorker.ts#L9

**Comment by outercloudstudio** [comment]
I'll look into using that.

**Comment by outercloudstudio** [comment]
I'm trying to use process.env.PUBLIC_URL to get to the path of the public folder but it returns undefined when I test it. Should I be using process.env.BASE_URL instead or is it just because I'm running the program on my local machine?

**Comment by outercloudstudio** [comment]
The latest commit should fix the current problem of audio being looked for in the wrong directory! I can't be 100% sure it works until it's deployed to the nightly build but it works locally.

**Review by solvedDev — CHANGES_REQUESTED** [review]
There's a stale file (`components/Audio/click5.ogg`). Once that's gone, the PR should be good to merge :)

**Review by solvedDev — APPROVED** [review]
LGTM

**Pull request merged**
