### PR TITLE
feat: add compileFiles function to @bridge/project

### PR DESCRIPTION
**Pull request by aexer0e**
## Description
The `compileFiles` function can be imported from the `@bridge/project` extension module to update and compile specific files

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have tested my changes and confirmed that they are working

### CODE REVIEW

**Comment by solvedDev** [comment]
I generally agree that this is something we should add but what's your motivation behind triggering the "saveFile" event afterwards? I think this would probably be better as a separate API call

**Comment by aexer0e** [comment]
I wanted a method for manually recompiling files into com.mojang, like a project refresh without the indexing files step. I'm not sure if I should rename the function or split it into two

**Comment by solvedDev** [comment]
Ah, so I think "fileSave" shouldn't trigger at all then :)
This event is meant for when a user manually saves a file. The PR looks good to merge otherwise once you've removed this code 👍

**Review by solvedDev — APPROVED** [review]
LGTM

**Comment by solvedDev** [comment]
Thanks; this will land in today's nightly build and v2.1

**Pull request merged**
