### PR TITLE
feat: native bridge. v2 builds

### PR DESCRIPTION
**Pull request by solvedDev**
## Summary
Provide users with the additional option to install bridge. v2 as a native app on Windows, Linux and MacOS.

## Tasks
- [x] Support com.mojang syncing
- [x] JSONDefaults setup is 2x slower
- [x] Toolbar on windows
- [x] saveOrDownload should use reveal_in_file_explorer method
- [x] Error upon clearing savedDataForVersion key & reloading app (probably caused by issue below)
- [x] Data fs doesn't always save directory entries correctly
- [x] Support openFolder
- [x] Warn users before closing app
- [x] Speed up com.mojang project loading on Tauri builds
- [x] Update updater URL to point to bridge-core/editor repo
- [x] brproject export is broken
- [x] Downloading files doesn't work

### CODE REVIEW

**Review by Joelant05 — CHANGES_REQUESTED** [review]
- Dash compilation to `com.mojang` appears to be broken; any changes I make aren't compiled to com.mojang until I manually press "Compile Changes" in the compiler window. It looks like "Restart Watch Mode" works for compiling to `com.mojang` but doesn't seem to compile correctly - using the ItemEquippedSensor component only makes changes to the item file, not the player or BP AC.

- The "Move to bridge. Folder" and "Move to Local Folder" options should be hidden on the Tauri build since it doesn't really make sense here, and using it just deletes the entire project.

- We should create a guide on how users can bring their existing projects to the Tauri build because I think there will be lots of confusion when users open the native build and don't see their projects, or an option to import them. Maybe we could have an option to select their existing bridge folder to move it into the native app's project folder.

- I think the "Open Project Folder" option behavior should reveal the project folder in File Explorer on the Tauri build, as opposed to opening it within bridge's directory viewer 

Apart from this, everything else appears to be working fine! 😄 

All testing was done on Windows

**Comment by Joelant05** [comment]
Also, I've noticed that when running the PWA build and using the "Force Data Download" dev option, an error is thrown
image

**Comment by solvedDev** [comment]
I'll tackle auto-importing projects in a separate PR. Still figuring out the best way to do this 👍

**Review by Joelant05 — APPROVED** [review]
Looks good now! 
One issue I was encountering was with the ItemEquippedSensor animation controller not updating in `com.mojang` when changing the component in the item behavior file and only working when pressing "Compile Changes". However I've realised that this is an issue with custom components generally and effects the current release too, I'll open a separate issue for this

**Pull request merged**
